#滚动弹幕的显示时间
scrolltime=40
#固定弹幕的显示时间
fixtime=5
#字体(名称两边不需要使用引号""括住)
fontname=思源黑体 Bold
#大小
fontsize=22
#阴影
shadow=0
#粗体
bold=yes
#全部弹幕的显示范围(0.0-1.0)
displayarea=0.1
#描边 0-4
outline=1
#透明度
opacity=0.6
#指定弹幕屏蔽词文件路径(black.txt)，支持绝对路径和相对路径。文件内容以换行分隔
##支持 lua 的正则表达式写法
blacklist_path=~~/script-opts/blacklist.txt
# 弹幕解析失败调用
fallback_server=https://dmku.hls.one